config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  resources :sales
  resources :quotes
  resources :cars
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :employee
  belongs_to :car
  belongs_to :customer
  has_one :sale
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  #load_and_authorize_resource
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:date, :car_sale_price, :interest_rate, :pay_period, :sold, :employee_id, :car_id, :customer_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :car_sale_price %>
    <%= form.text_field :car_sale_price %>
  </div>

  <div class="field">
    <%= form.label :interest_rate %>
    <%= form.text_field :interest_rate %>
  </div>

  <div class="field">
    <%= form.label :pay_period %>
    <%= form.number_field :pay_period %>
  </div>

  <div class="field">
    <%= form.label :sold %>
    <%= form.check_box :sold %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.text_field :car_id %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Car sale price</th>
      <th>Interest rate</th>
      <th>Pay period</th>
      <th>Sold</th>
      <th>Employee</th>
      <th>Car</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.date %></td>
        <td><%= quote.car_sale_price %></td>
        <td><%= quote.interest_rate %></td>
        <td><%= quote.pay_period %></td>
        <td><%= quote.sold %></td>
        <td><%= quote.employee %></td>
        <td><%= quote.car %></td>
        <td><%= quote.customer %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @quote.date %>
</p>

<p>
  <strong>Car sale price:</strong>
  <%= @quote.car_sale_price %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @quote.interest_rate %>
</p>

<p>
  <strong>Pay period:</strong>
  <%= @quote.pay_period %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @quote.sold %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>