config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  resources :sales
  resources :quotes
  resources :cars
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :quote
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  load_and_authorize_resource
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:data, :quote_id, :sales_tax, :total_price, :payment_method)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :quote_id %>
    <%= form.text_field :quote_id %>
  </div>

  <div class="field">
    <%= form.label :sales_tax %>
    <%= form.text_field :sales_tax %>
  </div>

  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Quote</th>
      <th>Sales tax</th>
      <th>Total price</th>
      <th>Payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.data %></td>
        <td><%= sale.quote %></td>
        <td><%= sale.sales_tax %></td>
        <td><%= sale.total_price %></td>
        <td><%= sale.payment_method %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @sale.data %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @sale.sales_tax %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @sale.total_price %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @sale.payment_method %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>