config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  resources :sales
  resources :quotes
  resources :cars
  resources :employees
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cis4339Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Rails Tutorial</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Cars", cars_path %></li>
                <li><%= link_to "Customers", customers_path %></li>
                <li><%= link_to "Sales", sales_path %></li>
                <li><%= link_to "Quotes", quotes_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
                <% if user_signed_in? %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
  </body>
</html>